[options]
db_host = odoo-db
db_port = 5432
db_user = odoo
db_password = odoo
db_sslmode = prefer
db_name = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo